### PR TITLE
Update naming for dbplyr 2

### PR DESCRIPTION
**Pull request by ndiquattro**
This updates the name of the sql translations to be compatible with dbplyr 2.

### CODE REVIEW

**Comment by hershelm** [comment]
Hey Nick, I was able to pass the tests by making the following changes: 

backend-snowflake.R
``` r
#' Snowflake Backend for dbplyr
#'
#' @param con Connection object to use
#'
#' @importFrom dbplyr sql_translation
#' @export
sql_translation.Snowflake <- function(con) {
  dbplyr::sql_variant(
    base_snowflake_scalar,
    base_snowflake_agg,
    base_snowflake_win
  )
}


#' @importFrom dbplyr dbplyr_edition
#' @export
dbplyr_edition.Snowflake <- function(con) {
  2L
}


base_snowflake_scalar <-
  dbplyr::sql_translator(
    .parent = dbplyr::base_odbc_scalar,

    # Stringr Functions -----
    str_detect = function(string, pattern, negate = FALSE) {
      if (negate) {
        return(dbplyr::sql_expr(NOT(CONTAINS(!!string, !!pattern))))
      }

      dbplyr::sql_expr(CONTAINS(!!string, !!pattern))
    },

    str_remove_all = function(string, pattern) {
      dbplyr::sql_expr(REGEXP_REPLACE(!!string, !!pattern))
    },

    str_starts = function(string, pattern, negate = FALSE) {
      if (negate) {
        return(dbplyr::sql_expr(NOT(STARTSWITH(!!string, !!pattern))))
      }

      dbplyr::sql_expr(STARTSWITH(!!string, !!pattern))
    },

    str_ends = function(string, pattern, negate = FALSE) {
      if (negate) {
        return(dbplyr::sql_expr(NOT(ENDSWITH(!!string, !!pattern))))
      }

      dbplyr::sql_expr(ENDSWITH(!!string, !!pattern))
    }
)

base_snowflake_agg <-
  dbplyr::sql_translator(
    .parent = dbplyr::base_odbc_agg,

    cor = dbplyr::sql_prefix("CORR"),
    cov = dbplyr::sql_prefix("COVAR_SAMP"),
    sd =  dbplyr::sql_prefix("STDDEV_SAMP"),
    var = dbplyr::sql_prefix("VAR_SAMP"),
    # all = dbplyr::sql_prefix("bool_and"),  # As found in snowflake repo
    # any = dbplyr::sql_prefix("bool_or"),
    paste = function(x, collapse)
      dbplyr::build_sql("LISTAGG(", x, collapse, ")")
    )

base_snowflake_win <-
  dbplyr::sql_translator(
    .parent = dbplyr::base_odbc_win,

    cor = dbplyr::sql_prefix("CORR"),
    cov = dbplyr::sql_prefix("COVAR_SAMP"),
    sd =  dbplyr::sql_prefix("STDDEV_SAMP"),
    var = dbplyr::sql_prefix("VAR_SAMP"),
    # all = dbplyr::sql_prefix("bool_and"),  # As found in snowflake repo
    # any = dbplyr::sql_prefix("bool_or"),
    paste = function(x, collapse)
      dbplyr::build_sql("LISTAGG(", x, collapse, ")")
  )
```


NAMESPACE
``` 
# Generated by roxygen2: do not edit by hand

S3method(dbplyr_edition,Snowflake)
S3method(sql_translation,Snowflake)
export("%>%")
export(flaky_connect)
export(flaky_current)
export(flaky_remove)
export(flaky_show)
export(flaky_show_ls)
export(flaky_use)
export(flaky_use_ls)
export(flaky_write)
importFrom(dbplyr,dbplyr_edition)
importFrom(dbplyr,sql_translation)
importFrom(magrittr,"%>%")
```

**Comment by ndiquattro** [comment]
Cool @hershelm ! Would you want to make a PR with the changes? I'll close this one.

**Comment by hershelm** [comment]
@ndiquattro would be happy to :)

could you give me permissions to write to the repo, then can file the PR?

**Comment by ndiquattro** [comment]
@hershelm I think you should be able to submit a PR from your fork? https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by hershelm** [comment]
@ndiquattro ah thanks, added the PR here: https://github.com/ndiquattro/flaky/pull/3

**Pull request closed without merging**
